"""initial schema: books, members, book_copies, loans

Hand-authored (not autogenerated) so the produced DDL matches
``docs/design/01-database.md`` §1 byte-for-byte. Highlights worth knowing:

* The ``copy_status`` Postgres enum is created up-front via ``op.execute``
  so the table column can reference an already-existing type. The matching
  ``DROP TYPE`` is in :func:`downgrade`.
* The functional indexes ``books_title_lower_idx`` and
  ``books_author_lower_idx`` are emitted via ``op.create_index`` with
  ``sa.text("lower(<col>)")`` expressions; alembic supports text-expressions
  as index column references on Postgres.
* ``members_email_unique_idx`` is a **case-insensitive** unique index on
  ``lower(email)`` — the canonical way to enforce that two staff don't add
  ``Bob@x.com`` and ``bob@x.com`` as different members.
* The structural defense against double-borrow is the partial unique index
  ``loans_one_active_per_copy_idx``: unique on ``copy_id`` but only for rows
  where ``returned_at IS NULL``. Emitted with ``postgresql_where=...``.
* All FKs use ``ON DELETE RESTRICT`` to match the design DDL.

Revision ID: 0001
Revises:
Create Date: 2026-05-05
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Name of the Postgres enum type. Centralized so upgrade/downgrade stay in
# sync if it ever gets renamed.
_COPY_STATUS_ENUM = "copy_status"
_COPY_STATUS_VALUES = ("AVAILABLE", "BORROWED", "LOST")


def upgrade() -> None:
    """Create all tables, indexes, and the copy_status enum.

    Creation order matters: parent tables (``books``, ``members``) before
    child tables (``book_copies``, ``loans``) so foreign keys resolve.
    """

    # ------------------------------------------------------------------
    # 1. books
    # ------------------------------------------------------------------
    op.create_table(
        "books",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            primary_key=True,
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("author", sa.Text(), nullable=False),
        sa.Column("isbn", sa.Text(), nullable=True),
        sa.Column("published_year", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )

    # Functional B-tree indexes on lower(...) for case-insensitive prefix
    # search. ``sa.text(...)`` lets us pass an expression where alembic
    # otherwise expects a column name.
    op.create_index(
        "books_title_lower_idx",
        "books",
        [sa.text("lower(title)")],
    )
    op.create_index(
        "books_author_lower_idx",
        "books",
        [sa.text("lower(author)")],
    )

    # ------------------------------------------------------------------
    # 2. members
    # ------------------------------------------------------------------
    op.create_table(
        "members",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            primary_key=True,
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )

    op.create_index(
        "members_email_unique_idx",
        "members",
        [sa.text("lower(email)")],
        unique=True,
    )

    # ------------------------------------------------------------------
    # 3. copy_status enum
    # ------------------------------------------------------------------
    # Emitted as raw SQL because Postgres ENUM creation is not naturally
    # represented by an alembic op. The matching DROP TYPE is in downgrade().
    enum_values_sql = ", ".join(f"'{v}'" for v in _COPY_STATUS_VALUES)
    op.execute(f"CREATE TYPE {_COPY_STATUS_ENUM} AS ENUM ({enum_values_sql})")

    # ------------------------------------------------------------------
    # 4. book_copies
    # ------------------------------------------------------------------
    # ``create_type=False`` is critical: the type already exists from the
    # CREATE TYPE above, so we tell SQLAlchemy not to try to create it again
    # while emitting CREATE TABLE. ``create_type`` is a Postgres-dialect-only
    # option, so we use ``postgresql.ENUM`` rather than the generic ``sa.Enum``
    # to ensure the flag is actually honored when alembic emits DDL.
    copy_status_pg_enum = postgresql.ENUM(
        *_COPY_STATUS_VALUES,
        name=_COPY_STATUS_ENUM,
        create_type=False,
    )

    op.create_table(
        "book_copies",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "book_id",
            sa.BigInteger(),
            sa.ForeignKey("books.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "status",
            copy_status_pg_enum,
            nullable=False,
            server_default=sa.text("'AVAILABLE'"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )

    op.create_index(
        "book_copies_book_id_status_idx",
        "book_copies",
        ["book_id", "status"],
    )

    # ------------------------------------------------------------------
    # 5. loans
    # ------------------------------------------------------------------
    op.create_table(
        "loans",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "copy_id",
            sa.BigInteger(),
            sa.ForeignKey("book_copies.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "member_id",
            sa.BigInteger(),
            sa.ForeignKey("members.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "borrowed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("returned_at", sa.DateTime(timezone=True), nullable=True),
    )

    # Partial unique index — the structural double-borrow guard. Only one
    # row per copy_id is allowed where returned_at IS NULL.
    op.create_index(
        "loans_one_active_per_copy_idx",
        "loans",
        ["copy_id"],
        unique=True,
        postgresql_where=sa.text("returned_at IS NULL"),
    )

    # Per-member active-loan lookup (for "what does this member have
    # checked out right now?"). Partial index keeps it tiny.
    op.create_index(
        "loans_member_active_idx",
        "loans",
        ["member_id"],
        postgresql_where=sa.text("returned_at IS NULL"),
    )

    # General indexes on FKs for member-history and copy-history queries.
    op.create_index("loans_member_id_idx", "loans", ["member_id"])
    op.create_index("loans_copy_id_idx", "loans", ["copy_id"])


def downgrade() -> None:
    """Reverse :func:`upgrade` cleanly.

    Drop order: child tables first (loans, book_copies), then parents
    (members, books), then the enum type. Indexes go away with their
    tables — alembic emits the ``DROP INDEX`` statements implicitly via
    ``drop_table``, but we drop the partial index on ``loans`` explicitly
    for clarity and because some setups warn on implicit drops of named
    indexes.
    """

    # loans (and its indexes — drop_table cleans these up, but be explicit
    # for the partial unique index since it's the most operationally
    # important one).
    op.drop_index("loans_copy_id_idx", table_name="loans")
    op.drop_index("loans_member_id_idx", table_name="loans")
    op.drop_index("loans_member_active_idx", table_name="loans")
    op.drop_index("loans_one_active_per_copy_idx", table_name="loans")
    op.drop_table("loans")

    # book_copies
    op.drop_index("book_copies_book_id_status_idx", table_name="book_copies")
    op.drop_table("book_copies")

    # The enum can be dropped now that no table references it.
    op.execute(f"DROP TYPE {_COPY_STATUS_ENUM}")

    # members
    op.drop_index("members_email_unique_idx", table_name="members")
    op.drop_table("members")

    # books
    op.drop_index("books_author_lower_idx", table_name="books")
    op.drop_index("books_title_lower_idx", table_name="books")
    op.drop_table("books")
